package com.comp603.shopping.utils;

import com.comp603.shopping.config.DBManager;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class DatabaseExporter {

    private static final String SCHEMA_FILE_PATH = "src/main/resources/schema.sql";

    // List of tables in dependency order (Parents first)
    // USERS -> ADDRESSES, PAYMENT_METHODS, ORDERS, SHOPPING_CART, WISHLIST
    // CATEGORIES -> PRODUCTS
    // PRODUCTS -> SHOPPING_CART, ORDER_ITEMS, WISHLIST
    // ORDERS -> ORDER_ITEMS, PAYMENTS
    private static final String[] TABLES = {
            "USERS",
            "ADDRESSES",
            "CATEGORIES",
            "PRODUCTS",
            "SHOPPING_CART",
            "ORDERS",
            "ORDER_ITEMS",
            "PAYMENTS",
            "WISHLIST",
            "PAYMENT_METHODS"
    };

    public static void main(String[] args) {
        exportDatabase();
    }

    public static void exportDatabase() {
        System.out.println("Starting database export...");

        File schemaFile = new File(SCHEMA_FILE_PATH);
        if (!schemaFile.exists()) {
            System.err.println("schema.sql not found at " + schemaFile.getAbsolutePath());
            return;
        }

        StringBuilder newSchemaContent = new StringBuilder();

        // 1. Read existing schema definition (CREATE TABLE statements)
        // We will read until we find the first INSERT or the "Seed Data" marker.
        try (BufferedReader reader = new BufferedReader(new FileReader(schemaFile))) {
            String line;
            boolean inSeedSection = false;
            while ((line = reader.readLine()) != null) {
                if (line.trim().startsWith("INSERT INTO") || line.contains("-- Seed Data")) {
                    inSeedSection = true;
                }

                if (!inSeedSection) {
                    // Replace GENERATED ALWAYS with GENERATED BY DEFAULT to allow explicit ID
                    // inserts
                    String modifiedLine = line.replace("GENERATED ALWAYS AS IDENTITY",
                            "GENERATED BY DEFAULT AS IDENTITY");
                    newSchemaContent.append(modifiedLine).append("\n");
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        // 2. Append new Seed Data from current Database
        try (Connection conn = DBManager.getConnection()) {
            if (conn == null) {
                System.err.println("Could not connect to database.");
                return;
            }

            newSchemaContent.append("\n-- Seed Data (Synced from Local DB)\n");

            for (String tableName : TABLES) {
                exportTableData(conn, tableName, newSchemaContent);
            }

            // 3. Add Sequence Restart commands
            newSchemaContent.append("\n-- Restart Sequences\n");
            for (String tableName : TABLES) {
                addSequenceRestart(conn, tableName, newSchemaContent);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            return;
        }

        // 4. Write back to schema.sql
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(schemaFile))) {
            writer.write(newSchemaContent.toString());
            System.out.println("Successfully updated " + SCHEMA_FILE_PATH);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void exportTableData(Connection conn, String tableName, StringBuilder sb) throws SQLException {
        String query = "SELECT * FROM " + tableName;
        try (Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(query)) {

            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Build column list
            List<String> columns = new ArrayList<>();
            String identityColumn = null;
            for (int i = 1; i <= columnCount; i++) {
                columns.add(metaData.getColumnName(i));
                // Try to guess identity column (usually ends with _ID and is first)
                if (i == 1 && metaData.isAutoIncrement(i)) {
                    identityColumn = metaData.getColumnName(i);
                }
            }
            String columnList = String.join(", ", columns);

            int rowCount = 0;
            while (rs.next()) {
                rowCount++;
                sb.append("INSERT INTO ").append(tableName).append(" (").append(columnList).append(") VALUES (");

                for (int i = 1; i <= columnCount; i++) {
                    Object value = rs.getObject(i);
                    if (value == null) {
                        sb.append("NULL");
                    } else if (value instanceof String || value instanceof Timestamp || value instanceof Date) {
                        sb.append("'").append(value.toString().replace("'", "''")).append("'");
                    } else {
                        sb.append(value.toString());
                    }

                    if (i < columnCount) {
                        sb.append(", ");
                    }
                }
                sb.append(");\n");
            }
            if (rowCount > 0) {
                sb.append("\n");
            }
        }
    }

    private static void addSequenceRestart(Connection conn, String tableName, StringBuilder sb) throws SQLException {
        // Find identity column
        String identityColumn = null;
        try (ResultSet rs = conn.getMetaData().getColumns(null, null, tableName, null)) {
            while (rs.next()) {
                if ("YES".equals(rs.getString("IS_AUTOINCREMENT"))) {
                    identityColumn = rs.getString("COLUMN_NAME");
                    break;
                }
            }
        }

        if (identityColumn != null) {
            // Get max id
            try (Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT MAX(" + identityColumn + ") FROM " + tableName)) {
                if (rs.next()) {
                    long maxId = rs.getLong(1);
                    // Restart at maxId + 1
                    long nextId = maxId + 1;
                    sb.append("ALTER TABLE ").append(tableName)
                            .append(" ALTER COLUMN ").append(identityColumn)
                            .append(" RESTART WITH ").append(nextId).append(";\n");
                }
            }
        }
    }
}
